name: 'Close Issue if Tracked Items are Closed'
description: 'A GitHub Action that looks at each item in a project and closes it if all of the "tracked" items are closed'
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Dependencies
      run: pip install -r requirements.txt
      shell: bash
    - name: Manual install of github-projectv2
      run: pip install -i https://test.pypi.org/simple/ projectv2
      shell: bash
    - name: Run the items check for tracking
      run: python src/check_items.py
      shell: bash