# .github/workflows/test_action.yaml
name: Check the state of the tracked items in the project
on: [push]

jobs:
  get-num-square:
    runs-on: ubuntu-latest
    name: Checks the "tracked" for each item in the project to see if they're all closed
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run the "track items" action
        id: check_tracks
        uses: ./
        env:
          GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}